//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDJam48.Var.Events
{
    using UnityEngine;
    using LDJam48.Var.Observe;
    using Util.Var;
    using Util.Var.Events;
    using Util.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Event/LDJam48.RunModel")]
    public sealed class RunModelGameEvent : GameEvent<LDJam48.RunModel>
    {
    }
    [System.Serializable()]
    public sealed class RunModelEventReference : EventReference<RunModelGameEvent, ObservableRunModelVariable, LDJam48.RunModel>
    {
    }
}
