//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDJam48.Var.Events
{
    using UnityEngine;
    using LDJam48.Var.Observe;
    using Util.Var.Events;
    
    [CreateAssetMenu(menuName = "Custom/Event/LDJam48.ScreenWipe")]
    public sealed class ScreenWipeGameEvent : GameEvent<LDJam48.ScreenWipe>
    {
    }
    [System.Serializable()]
    public sealed class ScreenWipeEventReference : EventReference<ScreenWipeGameEvent, ObservableScreenWipeVariable, LDJam48.ScreenWipe>
    {
    }
}
