//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDJam48.Var.Events
{
    using UnityEngine;
    using Util.Var.Events;
    
    public sealed class ScreenWipeGameEventListenerBehaviour : GameEventListenerBehaviour<LDJam48.ScreenWipe, ScreenWipeEventReference>
    {
    }
}
