//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Util.Var.Events;

namespace LDJam48.Var.Events
{
    using UnityEngine;
    using LDJam48.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Event/LDJam48.Tut.TutorialRequest")]
    public sealed class TutorialRequestGameEvent : GameEvent<LDJam48.Tut.TutorialRequest>
    {
    }
    [System.Serializable()]
    public sealed class TutorialRequestEventReference : EventReference<TutorialRequestGameEvent, ObservableTutorialRequestVariable, LDJam48.Tut.TutorialRequest>
    {
    }
}
