//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Util.Scenes;

namespace Util.Var
{
    using UnityEngine;
    using Util.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Variable/Util.Scene.SceneManagementRequest")]
    public sealed class SceneManagementRequestVariable : Variable<SceneManagementRequest>
    {
    }
    [System.Serializable()]
    public sealed class SceneManagementRequestReference : VariableReference<SceneManagementRequestVariable, ObservableSceneManagementRequestVariable, SceneManagementRequest>
    {
    }
}
