//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Var
{
    using UnityEngine;
    using Util.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Variable/LDJam48.ShakeDefinition")]
    public sealed class ShakeDefinitionVariable : Variable<LDJam48.ShakeDefinition>
    {
    }
    [System.Serializable()]
    public sealed class ShakeDefinitionReference : VariableReference<ShakeDefinitionVariable, ObservableShakeDefinitionVariable, LDJam48.ShakeDefinition>
    {
    }
}
