//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Var
{
    using UnityEngine;
    using Util.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Variable/Util.TweenDescription")]
    public sealed class TweenDescriptionVariable : Variable<Util.TweenDescription>
    {
    }
    [System.Serializable()]
    public sealed class TweenDescriptionReference : VariableReference<TweenDescriptionVariable, ObservableTweenDescriptionVariable, Util.TweenDescription>
    {
        public Pair<TweenBehaviour, int> BehaviourIndex;

        public bool IsBehaviouIndex => Delimeter == 3;
        public override TweenDescription Value
        {
            get
            {
                if (IsBehaviouIndex) return BehaviourIndex.First.GetTween(BehaviourIndex.Second);
                else return base.Value;
            }
            set
            {
                if (IsBehaviouIndex) BehaviourIndex.First.SetTween(BehaviourIndex.Second, value);
                else base.Value = value;
            }
        }
    }
}
