//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Var
{
    using UnityEngine;
    using Util.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Variable/Vector2")]
    public sealed class Vector2Variable : Variable<Vector2>
    {
    }
    [System.Serializable()]
    public sealed class Vector2Reference : VariableReference<Vector2Variable, ObservableVector2Variable, Vector2>
    {
    }
}
