//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Util.Variable;

namespace Util.Events
{
    using UnityEngine;
    
    [CreateAssetMenu(menuName = "Custom/Events/Util.AudioClipAsset")]
    public sealed class AudioClipAssetGameEvent : ObservableVariable<Util.AudioClipAsset>
    {
    }
}
