//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Util.Var.Observe;

namespace Util.Var.Events
{
    using UnityEngine;
    
    [CreateAssetMenu(menuName = "Custom/Event/Util.AudioClipAsset")]
    public sealed class AudioClipAssetGameEvent : GameEvent<Util.AudioClipAsset>
    {
    }

    [Serializable]
    public class AudioClipAssetGameEventReference : EventReference<AudioClipAssetGameEvent, ObservableAudioClipAsset, Util.AudioClipAsset>
    {

    }
}
