//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Util.Scenes;

namespace Util.Var.Events
{
    using UnityEngine;
    using Util.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Event/Util.Scene.SceneManagementRequest")]
    public sealed class SceneManagementRequestGameEvent : GameEvent<SceneManagementRequest>
    {
    }
    [System.Serializable()]
    public sealed class SceneManagementRequestEventReference : EventReference<SceneManagementRequestGameEvent, ObservableSceneManagementRequestVariable, SceneManagementRequest>
    {
    }
}
