//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Var.Events
{
    using UnityEngine;
    using Util.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Event/Vector2")]
    public sealed class Vector2GameEvent : GameEvent<Vector2>
    {
    }
    [System.Serializable()]
    public sealed class Vector2EventReference : EventReference<Vector2GameEvent, ObservableVector2Variable, Vector2>
    {
    }
}
