//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Util.Var;
using Util.Var.Events;
using Util.Var.Observe;

namespace LDJam48.Var.Observe
{
    using UnityEngine;
    
    [CreateAssetMenu(menuName = "Custom/Observable/LDJam48.RunModel")]
    public sealed class ObservableRunModelVariable : ObservableVariable<LDJam48.RunModel>
    {
    }
}
