//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDJam48.Var
{
    using UnityEngine;
    using Util.Var;
    using LDJam48.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Variable/LDJam48.ScreenWipe")]
    public sealed class ScreenWipeVariable : Variable<LDJam48.ScreenWipe>
    {
    }
    [System.Serializable()]
    public sealed class ScreenWipeReference : VariableReference<ScreenWipeVariable, ObservableScreenWipeVariable, LDJam48.ScreenWipe>
    {
    }
}
