//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Util.Var;

namespace LDJam48.Var
{
    using UnityEngine;
    using LDJam48.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Variable/LDJam48.Tut.TutorialRequest")]
    public sealed class TutorialRequestVariable : Variable<LDJam48.Tut.TutorialRequest>
    {
    }
    [System.Serializable()]
    public sealed class TutorialRequestReference : VariableReference<TutorialRequestVariable, ObservableTutorialRequestVariable, LDJam48.Tut.TutorialRequest>
    {
    }
}
